"""
A discovery sweep costs one sandbox, not one per pair.

Discovery tests every usable pair of columns, and every candidate became its
own sandboxed subprocess: a fresh Python, a fresh pandas import, and a fresh
copy of the whole dataset. Measured on this machine, one run costs 1.02s of
which 0.8s is process startup — the correlation itself is microseconds.

That is 820 runs for a 41-column file (14 minutes) and 4,950 for a
100-column one (about 84 minutes), serially, while a researcher watches a
spinner. It also copies the input file once per run: 32GB of I/O to read 40MB
of data. Every test in the suite used four columns, where six runs finish in
five seconds and nothing looks wrong.

The sandbox boundary is unchanged. These specs are generated by the system
from a closed list of methods — they are not user code — and running them in
one isolated process is the same isolation as running them in eight hundred.
What each candidate keeps is its own analysis run, its own recorded result and
its own seed, because that is what provenance rests on.
"""

from __future__ import annotations

import time
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from throughline_runtime.executor import SandboxPolicy, run_analysis, run_many

COLUMNS = 8


@pytest.fixture(scope="module")
def data(tmp_path_factory) -> Path:
    rng = np.random.default_rng(11)
    frame = pd.DataFrame(
        {f"var_{i}": rng.normal(size=2_000) for i in range(COLUMNS)})
    # One real relationship, so the batch has something true to find.
    frame["var_1"] = 0.9 * frame["var_0"] + rng.normal(scale=0.2, size=2_000)
    path = tmp_path_factory.mktemp("sweep") / "data.csv"
    frame.to_csv(path, index=False)
    return path


def _specs(n: int) -> list[dict]:
    pairs = [(i, j) for i in range(COLUMNS) for j in range(i + 1, COLUMNS)][:n]
    return [{"method": "pearson_correlation",
             "variables": {"x": f"var_{i}", "y": f"var_{j}"},
             "confidence_level": 0.95, "random_seed": 0}
            for i, j in pairs]


class TestOneSandboxForTheWholeSweep:
    def test_every_spec_comes_back(self, data):
        specs = _specs(12)
        batch = run_many(specs=specs, input_path=data, input_suffix=".csv")
        assert batch.ok, batch.stderr
        assert len(batch.payload["results"]) == len(specs)

    def test_each_result_is_what_a_single_run_would_have_produced(self, data):
        """
        The point of the sandbox is the number it returns. If batching changed
        one, nothing else here would matter.
        """
        specs = _specs(3)
        batch = run_many(specs=specs, input_path=data, input_suffix=".csv")
        for spec, got in zip(specs, batch.payload["results"]):
            alone = run_analysis(spec=spec, input_path=data, input_suffix=".csv")
            assert got["ok"] and alone.ok
            assert got["result"]["estimate"] == pytest.approx(
                alone.payload["result"]["estimate"])
            assert got["result"]["p_value"] == pytest.approx(
                alone.payload["result"]["p_value"])
            assert got["rows_used"] == alone.payload["rows_used"]

    def test_it_costs_about_one_process_not_twelve(self, data):
        """
        The measurement this exists for. Twelve specs in one sandbox must cost
        far less than twelve sandboxes — not a little less, or the change was
        not worth making.
        """
        one_start = time.perf_counter()
        run_analysis(spec=_specs(1)[0], input_path=data, input_suffix=".csv")
        single = time.perf_counter() - one_start

        many_start = time.perf_counter()
        run_many(specs=_specs(12), input_path=data, input_suffix=".csv")
        batched = time.perf_counter() - many_start

        assert batched < single * 4, (
            f"twelve batched specs took {batched:.2f}s against {single:.2f}s "
            f"for one alone — the startup is still being paid per pair")


class TestOneBadCandidateDoesNotSinkTheSweep:
    def test_a_failing_spec_is_reported_beside_the_others(self, data):
        """
        Eight hundred candidates and one bad column must not cost the sweep.
        Each entry carries its own verdict, exactly as a lone run does.
        """
        specs = _specs(2) + [{
            "method": "pearson_correlation",
            "variables": {"x": "var_0", "y": "no_such_column"},
            "confidence_level": 0.95, "random_seed": 0,
        }]
        batch = run_many(specs=specs, input_path=data, input_suffix=".csv")

        assert batch.ok, "one bad candidate took down the whole sweep"
        results = batch.payload["results"]
        assert [r["ok"] for r in results] == [True, True, False]
        assert "no_such_column" in results[-1]["error"]

    def test_an_unreadable_file_fails_the_whole_batch(self, tmp_path):
        """That one is not per-candidate: nothing can be computed."""
        missing = tmp_path / "not-here.csv"
        missing.write_text("this is not, in fact, a readable frame\x00\x00")
        batch = run_many(specs=_specs(2), input_path=missing,
                         input_suffix=".xlsx")
        assert not batch.ok or all(
            not r["ok"] for r in batch.payload.get("results", [{"ok": False}]))


def test_the_single_spec_path_still_works(data):
    """The batch is an addition. Nothing about one analysis has changed."""
    alone = run_analysis(spec=_specs(1)[0], input_path=data,
                         input_suffix=".csv", policy=SandboxPolicy())
    assert alone.ok
    assert alone.payload["result"]["estimate"] == pytest.approx(0.976, abs=0.05)


class TestTheBudgetIsRealAtEitherEnd:
    def test_a_long_sweep_is_given_room_to_finish(self):
        """A limit written for one correlation would kill a sweep midway."""
        from throughline_runtime.executor import (
            MAX_BATCH_TIMEOUT_SECONDS, SandboxPolicy, _run_sandbox,
        )
        import throughline_runtime.executor as executor

        seen: dict = {}
        original = executor._run_sandbox

        def capture(**kwargs):
            seen["policy"] = kwargs["policy"]
            return None

        executor._run_sandbox = capture
        try:
            executor.run_many(specs=[{}] * 200, input_path=Path("x"),
                              input_suffix=".csv")
            assert seen["policy"].timeout_seconds > SandboxPolicy().timeout_seconds
        finally:
            executor._run_sandbox = original

    def test_the_budget_does_not_become_no_budget(self):
        """
        Scaling per spec without a ceiling grants a 200-column sweep — 19,900
        pairs — eleven hours, which is not a limit. A sweep that has not
        finished in half an hour is wrong, not slow.
        """
        import throughline_runtime.executor as executor
        from throughline_runtime.executor import MAX_BATCH_TIMEOUT_SECONDS

        seen: dict = {}
        original = executor._run_sandbox
        executor._run_sandbox = lambda **kw: seen.setdefault("p", kw["policy"])
        try:
            executor.run_many(specs=[{}] * 19_900, input_path=Path("x"),
                              input_suffix=".csv")
        finally:
            executor._run_sandbox = original
        assert seen["p"].timeout_seconds == MAX_BATCH_TIMEOUT_SECONDS
        assert seen["p"].cpu_seconds == MAX_BATCH_TIMEOUT_SECONDS


def test_a_realistic_sweep_finishes_in_seconds(tmp_path):
    """
    The measurement this whole change exists for, at a size a researcher
    actually has. Twenty columns is 190 pairs; at the old cost that is a bit
    over three minutes, and every test in the suite used four columns.
    """
    rng = np.random.default_rng(5)
    cols = 20
    frame = pd.DataFrame({f"var_{i}": rng.normal(size=5_000)
                          for i in range(cols)})
    path = tmp_path / "wide.csv"
    frame.to_csv(path, index=False)

    specs = [{"method": "pearson_correlation",
              "variables": {"x": f"var_{i}", "y": f"var_{j}"},
              "confidence_level": 0.95, "random_seed": 0}
             for i in range(cols) for j in range(i + 1, cols)]
    assert len(specs) == 190

    started = time.perf_counter()
    batch = run_many(specs=specs, input_path=path, input_suffix=".csv")
    elapsed = time.perf_counter() - started

    assert batch.ok, batch.stderr
    assert sum(1 for r in batch.payload["results"] if r["ok"]) == 190
    assert elapsed < 20, (
        f"190 pairs took {elapsed:.1f}s; a sweep is paying per pair again")
