"""
The script that would produce the number again (§75).

The provenance log says *what was done*. This says it in a language a machine
runs, which is what a reviewer means by "can I reproduce this" and what a
collaborator means by "show me the code".

**It is generated from the recorded spec, never from prose.** The method, the
variables, the confidence level and the seed all come from `analysis_specs`
and `analysis_runs` — the same rows the run itself used — so the script and the
recorded number have one source rather than two that can disagree.

**It refuses what it cannot reproduce faithfully.** Twelve methods exist in the
runtime; this emits code only where the replay-capability contract declares an
eligible run. A script that looked like the analysis and quietly did something
else would be worse than no script at all, because it would be believed — and
this product exists to prevent exactly that class of claim.

**It states what it leaves out.** The script re-runs one analysis. It does not
re-run the sandbox, the assumption checks, or the multiple-comparison
correction that decided whether the result survived — and a reader who
believed otherwise would take a bare p-value for a finding, which is the
misreading the whole system is arranged against.
"""

from __future__ import annotations

from typing import Any

from . import replay_capability

#: Methods whose computation can be written out in full, and the call that
#: does it. This is an implementation map, not by itself a replay-support claim;
#: tests require it to agree with replay_capability.REPLAY_SUPPORTED_METHODS.
EMITTABLE: dict[str, str] = {
    "pearson_correlation": "stats.pearsonr",
    "spearman_correlation": "stats.spearmanr",
}


class CannotEmit(RuntimeError):
    """The recorded run lies outside the faithful replay-export boundary."""


HEADER = '''"""
{question}

Generated by Throughline from analysis run {run_id}.

This re-runs one analysis and prints its estimate and p-value. It does not
re-run the assumption checks, and it does not apply the multiple-comparison
correction that decided whether this result survived — a bare p-value here is
not a finding. See the provenance log for what else was recorded.

Method chosen because: {rationale}
"""

import pandas as pd
from scipy import stats

# The file this ran on. Point it at your copy; the recorded content hash was
# {content_hash}, so a different file is a different analysis.
FRAME = pd.read_csv({path!r})
'''

BODY = '''
x = pd.to_numeric(FRAME[{x!r}], errors="coerce")
y = pd.to_numeric(FRAME[{y!r}], errors="coerce")

# Listwise deletion, pairwise — the same rows the recorded run used. Dropping
# them separately would compare different subsets of the data.
paired = x.notna() & y.notna()
x, y = x[paired], y[paired]

estimate, p_value = {call}(x, y)
print(f"n = {{len(x)}}")
print(f"estimate = {{estimate:.6f}}")
print(f"p = {{p_value:.6g}}")
'''


def for_run(cur, run_id: str) -> str:
    """A runnable script for one replay-eligible recorded analysis, or refusal."""
    try:
        run = replay_capability.eligible_run(cur, run_id)
    except replay_capability.ReplayIneligible as exc:
        supported = ", ".join(sorted(replay_capability.REPLAY_SUPPORTED_METHODS))
        raise CannotEmit(f"{exc} Replay-supported methods: {supported}.") from exc

    method = str(run["method"])
    call = EMITTABLE.get(method)
    if call is None:
        # Defensive even though the registry-accounting test makes this a broken
        # build: never issue an artifact if classification and implementation drift.
        raise CannotEmit(
            f"{method} is declared replay-supported but has no exporter in this build."
        )

    variables = dict(run["variables"] or {})
    hashes = dict(run["input_hashes"] or {})
    return (
        HEADER.format(
            question=run["research_question"] or "An analysis.",
            run_id=run["id"],
            rationale=run["method_rationale"] or "not recorded",
            content_hash=hashes["dataset_content_hash"],
            path=run["filename"],
        )
        + BODY.format(x=variables["x"], y=variables["y"], call=call)
    )
