"""
The script that would produce the number again (§75).

The provenance log says *what was done*. This says it in a language a machine
runs, which is what a reviewer means by "can I reproduce this" and what a
collaborator means by "show me the code".

**It is generated from the recorded spec, never from prose.** The method, the
variables, the confidence level and the seed all come from `analysis_specs`
and `analysis_runs` — the same rows the run itself used — so the script and
the recorded number have one source rather than two that can disagree.

**It refuses what it cannot reproduce faithfully.** Twelve methods exist in the
runtime; this emits code for the ones whose computation is a few honest lines
of scipy or statsmodels, and refuses the rest by name. A script that looked
like the analysis and quietly did something else would be worse than no script
at all, because it would be believed — and this product exists to prevent
exactly that class of claim.

**It states what it leaves out.** The script re-runs one analysis. It does not
re-run the sandbox, the assumption checks, or the multiple-comparison
correction that decided whether the result survived — and a reader who
believed otherwise would take a bare p-value for a finding, which is the
misreading the whole system is arranged against.
"""

from __future__ import annotations

from typing import Any

#: Methods whose computation can be written out in full, and the call that
#: does it. Anything absent is refused rather than approximated.
EMITTABLE: dict[str, str] = {
    "pearson_correlation": "stats.pearsonr",
    "spearman_correlation": "stats.spearmanr",
}


class CannotEmit(RuntimeError):
    """The recorded method has no faithful short form."""


HEADER = '''"""
{question}

Generated by Throughline from analysis run {run_id}.

This re-runs one analysis and prints its estimate and p-value. It does not
re-run the assumption checks, and it does not apply the multiple-comparison
correction that decided whether this result survived — a bare p-value here is
not a finding. See the provenance log for what else was recorded.

Method chosen because: {rationale}
"""

import pandas as pd
from scipy import stats

# The file this ran on. Point it at your copy; the recorded content hash was
# {content_hash}, so a different file is a different analysis.
FRAME = pd.read_csv({path!r})
'''

BODY = '''
x = pd.to_numeric(FRAME[{x!r}], errors="coerce")
y = pd.to_numeric(FRAME[{y!r}], errors="coerce")

# Listwise deletion, pairwise — the same rows the recorded run used. Dropping
# them separately would compare different subsets of the data.
paired = x.notna() & y.notna()
x, y = x[paired], y[paired]

estimate, p_value = {call}(x, y)
print(f"n = {{len(x)}}")
print(f"estimate = {{estimate:.6f}}")
print(f"p = {{p_value:.6g}}")
'''


def for_run(cur, run_id: str) -> str:
    """A runnable script for one recorded analysis, or a refusal."""
    cur.execute(
        """
        SELECT r.id, r.status, r.input_hashes,
               s.method, s.variables, s.research_question, s.method_rationale,
               f.filename
          FROM analysis_runs r
          JOIN analysis_specs s ON s.id = r.spec_id
          LEFT JOIN dataset_versions dv
                 ON dv.id = (s.dataset_version_ids ->> 0)
          LEFT JOIN datasets d ON d.id = dv.dataset_id
          LEFT JOIN sources src ON src.id = d.source_id
          LEFT JOIN files f ON f.id = src.file_id
         WHERE r.id = %s
        """,
        (run_id,),
    )
    run = cur.fetchone()
    if not run:
        raise LookupError(f"Unknown analysis run: {run_id}")

    method = run["method"]
    if method not in EMITTABLE:
        raise CannotEmit(
            f"No script is written for {method}. Its computation is more than "
            f"a few lines and a short version would be a different analysis "
            f"wearing this one's name. The provenance log records what was "
            f"run; scripts exist for: {', '.join(sorted(EMITTABLE))}."
        )

    variables = run["variables"] or {}
    if not variables.get("x") or not variables.get("y"):
        raise CannotEmit(
            "This run records no x and y to correlate, so there is nothing to "
            "write out.")

    hashes = run["input_hashes"] or {}
    return (
        HEADER.format(
            question=run["research_question"] or "An analysis.",
            run_id=run["id"],
            rationale=run["method_rationale"] or "not recorded",
            content_hash=hashes.get("dataset_content_hash") or "not recorded",
            path=run["filename"] or "your-data.csv",
        )
        + BODY.format(x=variables["x"], y=variables["y"],
                      call=EMITTABLE[method])
    )
