"""
What a finding says once it leaves this system.

A note written into a reference library outlives the project that produced it.
It will be read years later, by the researcher who has forgotten the context and
possibly by a co-author who never had it, in a tool that knows nothing about
this platform and cannot resolve a link back into it. Everything needed to judge
the claim has to be inside the note, because nothing outside it will be there.

That single fact decides every choice in this file.

**The caveats travel with the claim, in the same breath.** A finding that
survived one look and a finding that survived thirty look identical once the
number is out of context, so the exploratory family size is stated next to the
result rather than in a footnote. Splitting a claim from its qualification is how
a hedged result becomes a confident one in transit — the reader takes the
sentence and leaves the asterisk.

**Nothing is described more strongly than it was recorded.** `causal_status` is
carried through verbatim, and a finding never assessed for causation says so. An
association reported without that word is read as a cause by a hurried reader,
and the note is exactly where a hurried reader meets it.

**No numbers are written by anything but the record.** Every figure comes from a
recorded row and is stated as the record has it. This is the same rule that
governs generated prose here, and it matters more, not less, when the destination
is outside the system: nothing downstream can re-resolve a value that was
transcribed wrongly.

**It says where it came from and when.** A finding is a claim about a dataset
version as it stood on a day. Six months later the dataset may have moved, and a
note carrying no provenance cannot be checked against anything.

The output is HTML because Zotero notes are HTML, and deliberately plain: a
handful of tags every reference manager renders, no classes, no styling. A note
that depends on a stylesheet is a note that looks broken in half the tools that
will open it.
"""

from __future__ import annotations

import html
from typing import Any

#: How a lifecycle status reads to someone outside this system. The stored
#: vocabulary is precise and internal; a reader in Zotero has no glossary.
#: These are the values of `FindingLifecycle` and nothing else. The dictionary
#: had drifted into a different vocabulary — `confirmed`, `refuted`,
#: `superseded` and `retracted`, of which `refuted` belongs to `ClaimStatus`
#: and `superseded` to artifact staleness — while `replicated`, `conflicted`
#: and `deprecated`, which findings really do hold, had no wording at all. A
#: replicated finding, the strongest state in the system, therefore left for
#: somebody's reference manager apologising for having no plain-language form.
#: A test asserts these keys and the enum are the same set.
_LIFECYCLE = {
    "candidate": "Candidate — not yet reviewed.",
    "exploratory": "Exploratory — generated by a sweep, not a stated hypothesis.",
    "validated": "Validated — checked against its assumptions.",
    "replicated": ("Replicated — validated, and then found again in data that "
                   "was not used to find it."),
    "conflicted": ("Conflicted — another result in the same project disagrees "
                   "with this one, and the disagreement is unresolved."),
    "deprecated": ("Deprecated — withdrawn from use in this project. It is "
                   "kept so that anything resting on it can still be traced."),
}

#: The values of `CausalStatus`, and the same drift had happened here — in the
#: field this product is most careful about. `associational` is a near-miss for
#: the real `association_only` and `causal_refuted` is not a value at all,
#: while `temporally_consistent`, `possible_causal` and `insufficient_evidence`
#: — the three qualified readings this note exists to convey carefully — had no
#: wording and left as "Recorded as possible_causal, which has no
#: plain-language equivalent here."
#:
#: Each sentence says what was established and stops there. Understating a
#: causal reading costs a reader some strength they were entitled to;
#: overstating one is the failure this whole product is built against.
_CAUSAL = {
    "not_assessed": ("Causation was not assessed. This is an association; "
                     "nothing here supports a causal reading of it."),
    "association_only": ("Association only. The design does not support a "
                         "causal claim."),
    "temporally_consistent": ("The supposed cause precedes the effect, which "
                              "rules out one alternative and establishes no "
                              "causal claim by itself."),
    "possible_causal": ("A causal reading is possible and is not established. "
                        "It survived the checks that were applied; those "
                        "checks cannot rule out an unmeasured common cause."),
    "causal_supported": ("A causal reading was assessed and supported under the "
                         "stated assumptions."),
    "insufficient_evidence": ("There was not enough evidence to assess a "
                              "causal reading either way. This is not a "
                              "finding of no effect."),
}


def _esc(value: Any) -> str:
    return html.escape(str(value if value is not None else ""), quote=False)


def render(finding: dict[str, Any], *, ledger: dict[str, Any] | None = None,
           provenance: dict[str, Any] | None = None) -> str:
    """
    A finding as a self-contained note.

    `ledger` is the exploration report for the session that produced this, and
    omitting it is not neutral: without it the note cannot say how many times the
    data was looked at, and a reader has no way to tell a first look from a
    thirtieth. When it is absent the note says so rather than implying the
    question does not apply.
    """
    title = _esc(finding.get("title") or "Untitled finding")
    parts = [f"<h2>{title}</h2>"]

    statement = finding.get("statement") or finding.get("summary") or ""
    if statement:
        parts.append(f"<p>{_esc(statement)}</p>")

    # The qualifications, before any detail. A reader who stops after two
    # paragraphs must not stop before the caveat.
    parts.append(f"<p><b>Status.</b> {_esc(_lifecycle(finding))}</p>")
    parts.append(f"<p><b>Causation.</b> {_esc(_causal(finding))}</p>")
    parts.append(f"<p><b>Multiple comparisons.</b> {_esc(_multiplicity(ledger))}</p>")

    limitations = finding.get("limitations") or []
    if limitations:
        items = "".join(f"<li>{_esc(item)}</li>" for item in limitations)
        parts.append(f"<p><b>Recorded limitations.</b></p><ul>{items}</ul>")
    else:
        # Silence here would read as "no limitations", which is a much stronger
        # statement than "none were written down".
        parts.append("<p><b>Recorded limitations.</b> None were recorded. That "
                     "is not the same as none applying.</p>")

    parts.append(f"<p><b>Provenance.</b> {_esc(_provenance(provenance))}</p>")
    parts.append(
        "<p><i>Written from a Throughline research record. The figures here "
        "come from recorded computations; the wording around them does not "
        "restate them.</i></p>")
    return "\n".join(parts)


def _lifecycle(finding: dict[str, Any]) -> str:
    status = (finding.get("lifecycle_status") or "candidate").lower()
    return _LIFECYCLE.get(
        status,
        f"{status} — an internal status with no plain-language equivalent "
        "recorded, so it is reproduced as stored rather than paraphrased.")


def causal_sentence(status: str | None) -> str:
    """What a causal status means, in one sentence a reader outside can use.

    Public because the researcher's own screen needs the same sentence, and a
    second copy of this vocabulary in the client is exactly the drift that put
    `associational` in here for a status really called `association_only`. One
    dictionary, served to both.
    """
    known = (status or "not_assessed").lower()
    return _CAUSAL.get(
        known,
        f"Recorded as {known}, which has no plain-language equivalent here. "
        "Treat it as an association unless the record says otherwise.")


def _causal(finding: dict[str, Any]) -> str:
    return causal_sentence(finding.get("causal_status"))


def _multiplicity(ledger: dict[str, Any] | None) -> str:
    """
    How many times the data was looked at, in the note itself.

    The number that changes how a p-value should be read, stated where the claim
    is rather than left behind in the workspace. A finding that survived one
    test and one that survived thirty are indistinguishable once the result is
    out of context, and this is precisely the moment it leaves.
    """
    if ledger is None:
        return ("Not recorded for this finding. Without the number of tests run "
                "in the session that produced it, the strength of this result "
                "cannot be judged from the note alone.")

    looks = ledger.get("looks", 0)
    family = ledger.get("family_size", 0)
    confirmatory = ledger.get("confirmatory", 0)

    if looks == 0:
        return "No tests were recorded in the session that produced this."
    if family == 0 and confirmatory:
        return (f"Tested against a hypothesis registered before the data was "
                f"examined, so it is not one of {looks} exploratory looks.")

    return (f"{looks} test{'' if looks == 1 else 's'} were run on this data in "
            f"the session that produced this finding, and {family} of them were "
            "corrected together as one family. A result found after many looks "
            "is weaker than the same result found first.")


def _provenance(provenance: dict[str, Any] | None) -> str:
    if not provenance:
        return ("No analysis run was recorded against this finding, so there is "
                "nothing to check it against later.")
    bits = []
    if provenance.get("analysis_run_id"):
        bits.append(f"analysis run {provenance['analysis_run_id']}")
    versions = provenance.get("dataset_version_ids") or []
    if isinstance(versions, str):
        versions = [versions]
    if versions:
        bits.append("dataset version "
                    + ", ".join(str(version) for version in versions))
    if provenance.get("method"):
        bits.append(f"method {provenance['method']}")
    if provenance.get("recorded_at"):
        bits.append(f"recorded {provenance['recorded_at']}")
    if not bits:
        return ("Recorded, but without an identifier that can be resolved "
                "later.")
    return (", ".join(bits)
            + ". The dataset may have changed since; this describes it as it "
              "stood then.")


def for_finding(cur, *, finding_id: str, enquiry_id: str | None = None
                ) -> dict[str, Any]:
    """
    Assemble the note for a stored finding.

    Reads the finding, its analysis provenance and — when a session is given —
    the exploration ledger for that session, then renders. Kept separate from
    `render` so the rendering can be tested without a database, which is most of
    what is worth testing here.
    """
    cur.execute(
        "SELECT id, title, statement, summary, lifecycle_status, causal_status, "
        "limitations FROM findings WHERE id = %s", (finding_id,))
    finding = cur.fetchone()
    if not finding:
        raise ValueError(f"No such finding: {finding_id}")

    # A finding reaches its analysis through the validation report that
    # promoted it: report → connection → run → spec. There is no direct link,
    # and inventing one would have been a plausible-looking query against
    # tables that do not exist.
    cur.execute(
        "SELECT c.analysis_run_id, c.method, vr.created_at AS recorded_at, "
        "s.dataset_version_ids "
        "FROM validation_reports vr "
        "JOIN connections c ON c.id = vr.connection_id "
        "LEFT JOIN analysis_runs ar ON ar.id = c.analysis_run_id "
        "LEFT JOIN analysis_specs s ON s.id = ar.spec_id "
        "WHERE vr.finding_id = %s ORDER BY vr.created_at DESC LIMIT 1",
        (finding_id,))
    provenance = cur.fetchone()

    ledger = None
    if enquiry_id:
        from .exploration import ledger as read_ledger
        ledger = read_ledger(cur, enquiry_id)

    return {
        "finding_id": finding_id,
        "html": render(dict(finding), ledger=ledger,
                       provenance=dict(provenance) if provenance else None),
    }


__all__ = ["for_finding", "render"]
